project:
  type: website
  output-dir: docs

website:
  title: "Veronika Romero"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: events.qmd
        text: My events

format:
  html:
    theme: pulse
    css: styles.css
    toc: true



