project:
  type: website
  output-dir: docs


website:
  title: "Veronika Romero"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: events.qmd
        text: My events
      - href: hobbies.qmd
        text: My hobbies

format:
  html:
    theme: pulse
    css: styles.css
    toc: true



